### ISSUE TITLE
Arreglar Modos de Juego 

### ISSUE THREAD

**Issue by UO283535** [Arquisoft/wiq_es05c#248]
David y yo nos hemos encargado de arreglar el modo de juego de pregunta diaria, para lo que hemos tenido que crear un nuevo endpoint /getQuestionDiaria, asi como un nuevo metodo en el historyService para almacenar el numero de preguntas diarias acertadas en la base de datos. 

Tambien se han hecho los cambios en webapp necesarios para garantizar el correcto funcionamiento.

**Comment by uo282189** [comment]
Falta por comprobar algunos modos de juego y arreglarlos para la presentacion
