### ISSUE TITLE
Desplegar proyecto en MV

### ISSUE THREAD

**Issue by uo282189** [Arquisoft/wiq_es05c#4]
Probar a desplegar el proyecto en una maquina virtual en azure.

**Comment by UO283535** [comment]
Tras haber desplegado la aplicación correctamente en una maquina virtual creada en Azure, ahora no funciona. En vista de los ocurrido, nos ponemos en contacto con el profesor, quedando a la espera de una posible solución.

**Comment by uo282189** [comment]
Lo arreglemos haciendo un re-run all jobs del último release
